image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: wissal260/projet_devops
  IMAGE_TAG: v1
  CI_REGISTRY: docker.io

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    - docker push $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

test:
  stage: test
  script:
    - docker run $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG python -m pytest

deploy:
  stage: deploy
  script:
    - echo "Deploying to production..."
    - docker pull $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 5000:5000 $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
  only:
    - master
